version: '3'
services:
  web:
    build: .
    volumes:
      - .:/var/www/cupom
    ports:
      - 80:80
    command: 'rails s -b 0.0.0.0 -p 80'
    links:
      - db
  db:
    image: postgres:10.3-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
